# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyOwnApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyOwnApp
  pod ‘Firebase’
  pod 'Firebase/Core'
  pod 'Firebase/Database’

  target 'MyOwnAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyOwnAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end



